# Config file for automatic testing at travis-ci.org

language: python
python: 3.7

dist: xenial # default "precise" distro doesn't include Java 8 for Elasticsearch 5

matrix:
  include:
    - env: TOX_ENV=py36-django-110-es6
      python: 3.6
    - env: TOX_ENV=py37-django-110-es6
      python: 3.7
    - env: TOX_ENV=py27-django-110-es6
      python: 2.7
    - env: TOX_ENV=py36-django-111-es6
      python: 3.6
    - env: TOX_ENV=py37-django-111-es6
      python: 3.7
    - env: TOX_ENV=py27-django-111-es6
      python: 2.7
    - env: TOX_ENV=py36-django-2-es6
      python: 3.6
    - env: TOX_ENV=py36-django-3-es6
      python: 3.6
    - env: TOX_ENV=py37-django-2-es6
      python: 3.7
    - env: TOX_ENV=py37-django-21-es6
      python: 3.7
    - env: TOX_ENV=py37-django-22-es6
      python: 3.7
    - env: TOX_ENV=py37-django-3-es6
      python: 3.7

cache: pip
env:
  global:
    - ES_APT_URL=https://artifacts.elastic.co/packages/7.x/apt

before_install:
  # work around https://github.com/travis-ci/travis-ci/issues/8363
  - pip install codecov
  - wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - echo "deb $ES_APT_URL stable main" | sudo tee -a /etc/apt/sources.list.d/elk.list
  - sudo apt-get remove --purge elasticsearch -y
  - sudo apt-get update && sudo apt-get install elasticsearch -y
  - sudo -i service elasticsearch restart

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# sleep for elasticsearch
before_script:
  - wget -q --waitretry=1 --retry-connrefused -T 100 -O - http://127.0.0.1:9200

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV -- --elasticsearch

after_success:
  - codecov -e $TOX_ENV
